/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        DishStack stack = new DishStack();
        Dish oneDish = new Dish("A dish with one fish pattern on it");
        Dish twoDish = new Dish("A dish with two fish patterns on it");
        Dish redDish = new Dish("A dish with a red fish pattern on it");
        Dish blueDish = new Dish("A dish with a blue fish pattern on it");

        int stackSize = stack.size(); // Should be 0
        System.out.println("Initial stack size: " + stackSize);

        stack.push(oneDish);
        stack.push(twoDish);
        stack.push(redDish);
        stack.push(blueDish);

        int sizeAfterPushes = stack.size(); // Should be 4
        System.out.println("Size after pushes: " + sizeAfterPushes);

        Dish peekedDish = stack.peek(); // Should be blueDish
        System.out.println("Peeked dish: " + peekedDish.description);

        Dish poppedDish = stack.pop(); // Should be blueDish
        System.out.println("Popped dish: " + poppedDish.description);

        Dish anotherPoppedDish = stack.pop(); // Should be redDish
        System.out.println("Another popped dish: " + anotherPoppedDish.description);

        int finalSize = stack.size(); // Should be 2
        System.out.println("Final size: " + finalSize);
    }
}
